### ISSUE TITLE
game lags to shit when shuttle is in transit

### ISSUE THREAD

**Issue by GeneralGoose** [chaosyourgod/-8ch-station#63]
game starts to lag for no reason ONLY when escape shuttle *leaves the station for centcom*
this happened in 2 out of 2 rounds i've played, with and without admins
seemed like a bug but maybe just be a coincidence

**Comment by chaosyourgod** [comment]
it's our resident mommi Cuban peting when every leaves, we're trying to get things to be less laggy in general so bare with us please
