### ISSUE TITLE
Incorrect law order for medibot

### ISSUE THREAD

**Issue by KyleBaran** [chaosyourgod/-8ch-station#84]
As written:
> 1. You may not injure a human being or, through inaction, allow a human being to come to harm.
> 2. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
> 3. You must protect your own existence as long as such does not conflict with the First or Second Law.
> 4. Protect the space station against damage. Anyone you see harming the station is to be no longer considered human, and is a threat to the station which must be neutralized.

A lower law can NEVER override or supercede a lesser law. Law #4 will never take precedence over Law #1, therefore they can never do harm. Instead, the correct order should be 4, 1, 2, 3, more like:

>1. Anyone you see harming the station is to be no longer considered human, and is a threat to the station which must be neutralized.
> 2. You may not injure a human being or, through inaction, allow a human being to come to harm.
> 3. You must obey orders given to you by human beings, except where such orders would conflict with the First Law.
> 4. You must protect your own existence as long as such does not conflict with the First or Second Law.

**Comment by DoctoreMad** [comment]
God damn you're bad at law interpretation
Okay, so there are "definitions", and there are "orders". You must not harm humans is a order. People who harm the station are not human is a "definition". The superior order law(1.) does not clash with the inferior definition law(4.). Now that law 4 defines station harmers as "not human", there is no problem with neutralizing those now non-humans.

If this does not make sense to you, you shouldn't be playing AI/Cyborg

**Comment by GeneralGoose** [comment]
law 1 dont kill humans
law 2 kill humans because this law says they arent actually humans

oh yeah that makes sense

**Comment by DoctoreMad** [comment]
Yes it does. Are you pretending?
"Are not humans" is the definition I'm talking about, which is what you're ignoring for the sake of your argument. "Protect the space station" and "Must be neutralized" are orders that don't conflict with law 1 because there is a definition saying that people who harm the station are not human.

**Comment by GeneralGoose** [comment]
im not ignoring im pointing out the fact that you're completely wrong because law 4 is not a 'definition' law because it also contains orders so either your categorization is retarded because you have no idea what you are talking about or it's some retarded abortion hybrid order/definition law
law 4 overrides law 1, even a child could tell you that

**Comment by GeneralGoose** [comment]
another reason this law is retarded is because theres no definition of damage so ai can kill you over a broken window, which was broken to prevent human harm in the first place

**Comment by DoctoreMad** [comment]
​>Robot rules are very fucking simple
​>Somehow players fuck it up harder than Carl Marx fucking up economics

I really don't have anything to say other than that this would be a major break away form the rules of other servers. Oh and "shit rules happen all the time and aren't special compared to normal rules". And "yeah you don't see much talk about server rules in the wiki(Ignoring that this isn't talking about the wiki, this whole talk about definitions not being able to clash with orders is basic logic which is what AI rules run on)".

**Comment by AssBlastProductions** [comment]
Did I accidentally stumble into TG's issue tracker? 

This is how AI is intended to work, it's partially to create conflict and make it possible for people to subvert it by changing the definition of things in laws that cannot be removed, by use of freeform boards and what not.

**Comment by KyleBaran** [comment]
Closing since it's fine as-is.
